name: Build docker image
on:
  push:
    paths:
      - ".github/workflows/docker.yml"
      - "Dockerfile"
      - "cmd/**"
      - "pkg/**"
      - "go.mod"
      - "go.sum"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build -t rinx/vald-meta-halodb .
    - name: login to DockerHub
      run: |
        echo ${DOCKERHUB_PASS} | docker login --username ${DOCKERHUB_USER} --password-stdin
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    - name: push to DockerHub (master)
      if: github.ref == 'refs/heads/master'
      run: |
        docker tag rinx/vald-meta-halodb rinx/vald-meta-halodb:nightly
        docker push rinx/vald-meta-halodb:nightly
    - name: push to DockerHub (pull request)
      if: github.event_name == 'pull_request'
      run: |
        pr_num=`cat $GITHUB_EVENT_PATH | jq -r ".number"`
        docker tag rinx/vald-meta-halodb rinx/vald-meta-halodb:pr-${pr_num}
        docker push rinx/vald-meta-halodb:pr-${pr_num}
    - name: push to DockerHub (tags)
      if: startsWith( github.ref, 'refs/tags/')
      run: |
        docker push rinx/vald-meta-halodb:latest
        tag_name=`echo $GITHUB_REF | sed -e 's:^refs/tags/::'`
        docker tag rinx/vald-meta-halodb rinx/vald-meta-halodb:${tag_name}
        docker push rinx/vald-meta-halodb:${tag_name}
        docker tag rinx/vald-meta-halodb rinx/vald-meta-halodb:nightly
        docker push rinx/vald-meta-halodb:nightly
